---
# =================================================================================================
# Area labels
# =================================================================================================
- name: area/github
  color: "000000" # github black
  description: Changes made in the github directory
- name: area/terraform
  color: "844FBA" # terraform purple
  description: Changes made in the infrastructure directory


# =================================================================================================
# Device Labels
# =================================================================================================
- name: device/rb5009
  color: "111111"
  description: Changes to the config for the RB5009.
- name: device/cap-ax
  color: "333333"
  description: Changes to the config for the cAP AX.
- name: device/crs326
  color: "555555"
  description: Changes to the config for the CRS326.
- name: device/crs317
  color: "777777"
  description: Changes to the config for the CRS317.
- name: device/hex
  color: "999999"
  description: Changes to the config for the HEX.


# =================================================================================================
# Issue Types
# =================================================================================================
- name: Bug
  color: "ff0000"
- name: Feature
  color: "00ff00"
- name: Chore
  color: "0000ff"
