[tools]
# Terraform Stuff
terraform = "1.10.4"
tf-summarize = "0.3.14"

# Miscellaneous Tools
age = "1.2.1"
sops = "3.9.3"
actionlint = "1.7.7"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"


# =================================================================================================
# TASKS
# =================================================================================================
[tasks.decrypt]
description = "Decrypt the terraform state and vars files."
run = [
    "sops --decrypt terraform.tfstate.sops > terraform.tfstate",
    "sops --decrypt credentials.auto.tfvars.sops > credentials.auto.tfvars"
]

[tasks.encrypt]
description = "Encrypt the terraform state and vars files."
run = [
    "sops --encrypt terraform.tfstate > terraform.tfstate.sops",
    "sops --encrypt credentials.auto.tfvars > credentials.auto.tfvars.sops"
]

[tasks.plan]
description = "Run and summarize terraform plan"
dir = ""
run = "terraform plan -out=tfplan && tf-summarize tfplan && rm tfplan"