[tools]
# Terraform Stuff
"aqua:hashicorp/terraform" = "latest"
"aqua:dineshba/tf-summarize" = "latest"

# Miscellaneous Tools
"aqua:FiloSottile/age" = "latest"
"aqua:getsops/sops" = "latest"


# =================================================================================================
# TASKS
# =================================================================================================
[tasks.decrypt]
description = "Decrypt the terraform state and vars files."
sources = ["terraform.tfstate", "credentials.auto.tfvars"]
outputs = ["terraform.tfstate.sops", "credentials.auto.tfvars.sops"]
run = [
    "sops --decrypt terraform.tfstate.sops > terraform.tfstate",
    "sops --decrypt credentials.auto.tfvars.sops > credentials.auto.tfvars"
]

[tasks.encrypt]
description = "Encrypt the terraform state and vars files."
outputs = ["terraform.tfstate", "credentials.auto.tfvars"]
sources = ["terraform.tfstate.sops", "credentials.auto.tfvars.sops"]
run = [
    "sops --encrypt terraform.tfstate > terraform.tfstate.sops",
    "sops --encrypt credentials.auto.tfvars > credentials.auto.tfvars.sops"
]

[tasks.plan]
description = "Run and summarize terraform plan"
dir = ""
run = "terraform plan -out=tfplan && tf-summarize tfplan && rm tfplan"