---
version: "3"

env:
  SOPS_AGE_KEY_FILE: ./age.key

tasks:
  encrypt:
    cmds:
      - sops --encrypt terraform.tfstate > terraform.tfstate.sops
      - sops --encrypt credentials.auto.tfvars > credentials.auto.tfvars.sops

  decrypt:
    cmds:
      - sops --decrypt terraform.tfstate.sops > terraform.tfstate
      - sops --decrypt credentials.auto.tfvars.sops > credentials.auto.tfvars

  init: terraform init -upgrade

  plan:
    cmds:
      - task decrypt
      - terraform plan
      - task encrypt

  apply:
    cmds:
      - task decrypt
      - terraform apply
      - task encrypt

  lint:
    cmds:
      - terraform fmt -recursive
      - terraform validate
