---
version: 3

env:
  SOPS_AGE_KEY_FILE: age.key

tasks:
  sops:decrypt:
    desc: Decrypt the terraform state and vars files.
    aliases: [ "sops:dec", "sops:d" ]
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - sops --decrypt tfstate.sops.json > tfstate.json
      - sops --decrypt credentials.auto.tfvars.sops > credentials.auto.tfvars

  sops:encrypt:
    desc: Encrypt the terraform state and vars files.
    aliases: [ "sops:enc", "sops:e" ]
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - sops --encrypt tfstate.json > tfstate.sops.json
      - sops --encrypt credentials.auto.tfvars > credentials.auto.tfvars.sops
