---
version: 3

env:
  SOPS_AGE_KEY_FILE: age.key

tasks:
  sops:encrypt:
    desc: Encrypt all sops files in this repository.
    aliases: ["sops:enc", "sops:e"]
    run: once
    cmd: bash {{.TASKFILE_DIR}}/.scripts/sops-encrypt-all.sh

  sops:decrypt:
    desc: Decrypt all sops files in this repository.
    aliases: ["sops:dec", "sops:d"]
    run: once
    cmd: bash {{.TASKFILE_DIR}}/.scripts/sops-decrypt-all.sh {{.CLI_ARGS}}
