include "root" {
  path = find_in_parent_folders("root.hcl")
}

dependency "router" {
  config_path = find_in_parent_folders("mikrotik/router-services")
}

terraform {
  source = find_in_parent_folders("modules/1password-item")
}

inputs = {
  op_service_account_token = get_env("OP_SERVICE_ACCOUNT_TOKEN")

  vault = "Badoink"
  items = {
    "WiFi - Badoink" = {
      password = dependency.router.outputs.untrusted_wifi_password
      notes    = "Auto-generated by Terraform"
    }
    "WiFi - Guest" = {
      password = dependency.router.outputs.guest_wifi_password
      notes    = "Auto-generated by Terraform"
    }
  }
}
