include "root" {
  path = find_in_parent_folders("root.hcl")
}

dependency "capsman" {
  config_path = find_in_parent_folders("mikrotik/router-base/services/capsman")
}

terraform {
  source = find_in_parent_folders("modules/1password-item")
}

inputs = {
  op_service_account_token = get_env("OP_SERVICE_ACCOUNT_TOKEN")

  vault = "Badoink"
  items = {
    "WiFi - Badoink" = {
      password = dependency.capsman.outputs.wifi_passphrases["home"]
      notes    = "Auto-generated by Terraform"
    }
    "WiFi - Guest" = {
      password = dependency.capsman.outputs.wifi_passphrases["guest"]
      notes    = "Auto-generated by Terraform"
    }
  }
}
