include "root" {
  path = find_in_parent_folders("root.hcl")
}

dependency "capsman" {
  config_path = find_in_parent_folders("mikrotik/router-rb5009/services/capsman")
}

dependency "switch-crs326" {
  config_path = find_in_parent_folders("mikrotik/switch-crs326")
}

dependency "switch-hex" {
  config_path = find_in_parent_folders("mikrotik/switch-hex")
}

dependency "switch-crs317" {
  config_path = find_in_parent_folders("mikrotik/switch-crs317")
}

dependency "router-rb5009" {
  config_path = find_in_parent_folders("mikrotik/router-rb5009")
}

terraform {
  source = find_in_parent_folders("modules/1password-item")
}

inputs = {
  op_service_account_token = get_env("OP_SERVICE_ACCOUNT_TOKEN")

  vault = "Badoink"
  items = merge(
    {
      "WiFi - Badoink" = {
        password = dependency.capsman.outputs.wifi_passphrases["home"]
        notes    = "Auto-generated by Terraform"
      }
      "WiFi - Guest" = {
        password = dependency.capsman.outputs.wifi_passphrases["guest"]
        notes    = "Auto-generated by Terraform"
      }
    },
    {
      for user, pass in dependency.switch-crs326.outputs.user_passwords :
      "Mikrotik CRS326 ${user} password" => {
        password = pass
        notes    = "Generated by Terraform for Mikrotik CRS326 device"
      }
    },
    {
      for user, pass in dependency.switch-hex.outputs.user_passwords :
      "Mikrotik HEX ${user} password" => {
        password = pass
        notes    = "Generated by Terraform for Mikrotik HEX device"
      }
    },
    {
      for user, pass in dependency.switch-crs317.outputs.user_passwords :
      "Mikrotik CRS317 ${user} password" => {
        password = pass
        notes    = "Generated by Terraform for Mikrotik CRS317 device"
      }
    },
    {
      for user, pass in dependency.router-rb5009.outputs.user_passwords :
      "Mikrotik Router ${user} password" => {
        password = pass
        notes    = "Generated by Terraform for Mikrotik Router device"
      }
    }
  )
}
