---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Actionlint

on:
  workflow_dispatch: {}
  pull_request: {}

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@v2.1.2
      
      - name: Run actionlint
        run: actionlint
