---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  # When a pull request is opened, reopened, or synchronized
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@fff460c54de9bc557d89108af5b6e093629f9605 # v3.4.48
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
