---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Labeler

on:
  # When a pull request is opened, reopened, or synchronized
  pull_request_target: {}

jobs:
  pr-labeler:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-labeler.yaml@b5cfdde4fbd3a009c30444b916ebe6f98a0a977f # v3.8.1
    secrets: inherit
    with:
      config-file: .github/labeler.yaml
