---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Job

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  # TODO: terraform lint here
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@fd0e201057ff688f30c9e00c08bbf407b811b96a # v3.4.49
    secrets: inherit

  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@fd0e201057ff688f30c9e00c08bbf407b811b96a # v3.4.49
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@fd0e201057ff688f30c9e00c08bbf407b811b96a # v3.4.49
    secrets: inherit
