---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  pull_request: { branches: [main] }
  push: {}

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup mise
        uses: jdx/mise-action@156251fcc627ac4e26cb0f93dd47d1d4979abf24 # v3.3.0

      - name: Run actionlint
        run: mise exec -- actionlint

  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup mise
        uses: jdx/mise-action@156251fcc627ac4e26cb0f93dd47d1d4979abf24 # v3.3.0
      
      - name: Run terraform fmt
        run: mise exec -- terraform fmt -recursive -check

  terragrunt-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup mise
        uses: jdx/mise-action@156251fcc627ac4e26cb0f93dd47d1d4979abf24 # v3.3.0
      
      - name: Run terragrunt fmt
        run: mise exec -- terragrunt hcl format --check
