---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Job

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  # TODO: terraform lint here
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@fff460c54de9bc557d89108af5b6e093629f9605 # v3.4.48
    secrets: inherit

  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@fff460c54de9bc557d89108af5b6e093629f9605 # v3.4.48
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@fff460c54de9bc557d89108af5b6e093629f9605 # v3.4.48
    secrets: inherit
