---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Job

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  # TODO: terraform lint here
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
    secrets: inherit

  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@9ce913356128f964413b5fe99efe4858e18d7831 # v3.4.51
    secrets: inherit
