---
name: Lint
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push: {}

jobs:
  check:
    runs-on: ubuntu-latest
    container: ghcr.io/mirceanton/actions-runner:2.335
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup mise
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          command: mise install
          max_attempts: 3
          timeout_minutes: 3

      - name: Run linters
        run: task lint:check
