---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Job

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  # TODO: terraform lint here
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@9636dd03edf5f6a14372182c4c07985c85485b9f # v3.4.50
    secrets: inherit

  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@9636dd03edf5f6a14372182c4c07985c85485b9f # v3.4.50
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@9636dd03edf5f6a14372182c4c07985c85485b9f # v3.4.50
    secrets: inherit
