---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Job

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  # TODO: terraform lint here
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@03898112670be8cb0d0f94d80b3c3aa6dbdc12d7 # v3.4.43
    secrets: inherit

  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@03898112670be8cb0d0f94d80b3c3aa6dbdc12d7 # v3.4.43
    secrets: inherit

  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@03898112670be8cb0d0f94d80b3c3aa6dbdc12d7 # v3.4.43
    secrets: inherit
