---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Lint Job

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  actionlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-actionlint.yaml@09f31ab6340ce5651dc6c28512a82de6b2415fb9 # v3.8.2
  markdownlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-markdownlint.yaml@09f31ab6340ce5651dc6c28512a82de6b2415fb9 # v3.8.2
    with: { config-file: ./.github/configs/.markdownlint.yaml }
  commitlint:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-commitlint.yaml@09f31ab6340ce5651dc6c28512a82de6b2415fb9 # v3.8.2
    with: { config-file: ./.github/configs/commitlint.config.mjs }
  terraform:
    uses: mirceanton/reusable-workflows/.github/workflows/reusable-terraform-fmt.yaml@09f31ab6340ce5651dc6c28512a82de6b2415fb9 # v3.8.2
