---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terraform

on:
  workflow_dispatch: {}
  pull_request: {}

permissions:
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@4d056cf31b20dbda64e7e44dc5da5565707b00d3 # v2.1.2
      
      - name: Run terraform fmt
        run: terraform fmt -recursive -check

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@4d056cf31b20dbda64e7e44dc5da5565707b00d3 # v2.1.2
      
      - name: Initialize workspace
        run: terraform init
        
      - name: Validate configuration
        run: terraform validate
