---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Terraform
permissions: { contents: read }

on:
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/terraform.yaml"
      - mise.toml
      - "*.tf"
      - "*.hcl"

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1
      
      - name: Run terraform fmt
        run: mise exec -- terraform fmt -recursive -check

  terragrunt-format:
    runs-on: ubuntu-latest
    needs: terraform-fmt
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup mise
        uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1
      
      - name: Run terragrunt fmt
        run: mise exec -- terragrunt hcl format --check
